version: '3.8'  # Especifica a versão do Docker Compose a ser usada

services:
  config-server-1:
    image: mongo:latest
    container_name: config-server-1
    command: ["mongod", "--configsvr", "--replSet", "config-repl-set", "--port", "27017"]
    networks:
      - mongo-cluster-network

  config-server-2:
    image: mongo:latest
    container_name: config-server-2
    command: ["mongod", "--configsvr", "--replSet", "config-repl-set", "--port", "27017"]
    networks:
      - mongo-cluster-network

  config-server-3:
    image: mongo:latest
    container_name: config-server-3
    command: ["mongod", "--configsvr", "--replSet", "config-repl-set", "--port", "27017"]
    networks:
      - mongo-cluster-network

  shard1-a:
    image: mongo:latest
    container_name: shard1-a
    command: ["mongod", "--shardsvr", "--replSet", "shard1-repl-set", "--port", "27018"]
    networks:
      - mongo-cluster-network

  shard1-b:
    image: mongo:latest
    container_name: shard1-b
    command: ["mongod", "--shardsvr", "--replSet", "shard1-repl-set", "--port", "27018"]
    networks:
      - mongo-cluster-network

  shard2-a:
    image: mongo:latest
    container_name: shard2-a
    command: ["mongod", "--shardsvr", "--replSet", "shard2-repl-set", "--port", "27019"]
    networks:
      - mongo-cluster-network

  shard2-b:
    image: mongo:latest
    container_name: shard2-b
    command: ["mongod", "--shardsvr", "--replSet", "shard2-repl-set", "--port", "27019"]
    networks:
      - mongo-cluster-network

  shard3-a:
    image: mongo:latest
    container_name: shard3-a
    command: ["mongod", "--shardsvr", "--replSet", "shard3-repl-set", "--port", "27020"]
    networks:
      - mongo-cluster-network

  shard3-b:
    image: mongo:latest
    container_name: shard3-b
    command: ["mongod", "--shardsvr", "--replSet", "shard3-repl-set", "--port", "27020"]
    networks:
      - mongo-cluster-network

  mongos-router-1:
    image: mongo:latest
    container_name: mongos-router-1
    command: ["mongos", "--configdb", "config-repl-set/config-server-1:27017,config-server-2:27017,config-server-3:27017", "--bind_ip_all"]
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster-network

  mongos-router-2:
    image: mongo:latest
    container_name: mongos-router-2
    command: ["mongos", "--configdb", "config-repl-set/config-server-1:27017,config-server-2:27017,config-server-3:27017", "--bind_ip_all"]
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster-network

  mongos-router-3:
    image: mongo:latest
    container_name: mongos-router-3
    command: ["mongos", "--configdb", "config-repl-set/config-server-1:27017,config-server-2:27017,config-server-3:27017", "--bind_ip_all"]
    ports:
      - "27020:27017"
    networks:
      - mongo-cluster-network

networks:
  mongo-cluster-network:
    driver: bridge
